[package]
name = "owlcom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio ={version="1",features = ["full"]}
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.79"
libp2p = "0.46.1"
reqwest = {version = "0.11.11", features=["json","multipart","stream"]}